name: quran_mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+2

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # State management, DI, and navigation
  get: ^4.7.3

  # Networking and HTTP comunication
  dio: ^5.9.2

  # Date formatting and date picker
  intl: ^0.20.2

  # Audio player
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17

  # Development utility for generating application launcher icons
  flutter_launcher_icons: ^0.14.4
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "assets/image/arabic-logo.png"

  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/image/arabic-logo.png"
